version: '3.4'

volumes:
  postgres_data:
      driver: local
  pgadmin-data:

services:
  healthapp:
    image: ${DOCKER_REGISTRY-}healthapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432
        POSTGRES_DATABASE: HealthApp
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: psltest
  postgres:
      image: postgres:16.1
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: psltest
        POSTGRES_DB: HealthApp
      healthcheck:
        test: ["CMD-SHELL", "pg_isready"]
        interval: 5s
        timeout: 2s
        retries: 5
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin