version: '3.4'

volumes:
  postgres_data:
      driver: local
  pgadmin-data:
  # minio-storage:
  # rabbitmq-storage:
  # opensearch-data:
  prometheus_data: {}
  grafana_data: {}

services:
  portal:
    image: ${DOCKER_REGISTRY-}portal
    container_name: portal
    build:
      context: .
      dockerfile: Portal/Dockerfile
    ports:
    - 58768:80
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.1
    volumes:
    - postgres_data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: keycloak
    healthcheck:
        test: ["CMD-SHELL", "pg_isready"]
        interval: 5s
        timeout: 2s
        retries: 5

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    volumes:
    #  - ./prometheus/:/etc/prometheus/
      - './portal/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
      - prometheus_data:/prometheus
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    #volumes:
    #- ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana
    user: root
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - default